// BannerComponent as initially generated by the CLI
import { Component } from '@angular/core';

@Component({
  selector: 'app-banner-test',
  template: '<p>banner works!</p>',
  styles: [],
})
export class BannerTestComponent {}
